---
- name: Check if SQL Server password secret exists
  shell: docker secret inspect sql_sa_password 2>/dev/null || echo "NOT_FOUND"
  register: sql_secret_check
  changed_when: false
  ignore_errors: true

- name: Create SQL Server password secret
  shell: echo "{{ sql_sa_password }}" | docker secret create sql_sa_password -
  when: "'NOT_FOUND' in sql_secret_check.stdout"

- name: Check if RabbitMQ user secret exists
  shell: docker secret inspect rabbitmq_user 2>/dev/null || echo "NOT_FOUND"
  register: rabbitmq_user_check
  changed_when: false
  ignore_errors: true

- name: Create RabbitMQ user secret
  shell: echo "{{ rabbitmq_user }}" | docker secret create rabbitmq_user -
  when: "'NOT_FOUND' in rabbitmq_user_check.stdout"

- name: Check if RabbitMQ password secret exists
  shell: docker secret inspect rabbitmq_pass 2>/dev/null || echo "NOT_FOUND"
  register: rabbitmq_pass_check
  changed_when: false
  ignore_errors: true

- name: Create RabbitMQ password secret
  shell: echo "{{ rabbitmq_pass }}" | docker secret create rabbitmq_pass -
  when: "'NOT_FOUND' in rabbitmq_pass_check.stdout"

- name: Check if Cloudflare tunnel token secret exists
  shell: docker secret inspect cloudflare_tunnel_token 2>/dev/null || echo "NOT_FOUND"
  register: tunnel_token_check
  changed_when: false
  ignore_errors: true

- name: Create Cloudflare tunnel token secret
  shell: echo "{{ tunnel_token }}" | docker secret create cloudflare_tunnel_token -
  when: "'NOT_FOUND' in tunnel_token_check.stdout"
