---
- name: Add Tailscale GPG key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: present

- name: Add Tailscale repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install Tailscale
  apt:
    name: tailscale
    state: present

- name: Check if Tailscale is already authenticated
  command: tailscale status
  register: tailscale_status
  ignore_errors: yes
  changed_when: false

- name: Authenticate Tailscale
  command: tailscale up --authkey={{ tailscale_authkey }} --accept-routes
  when: tailscale_status.rc != 0
  notify: Enable Tailscale

- name: Ensure Tailscale is running
  service:
    name: tailscaled
    state: started
    enabled: yes
