[swarm_manager]
100.99.158.16 ansible_user=kaka-server

[swarm_workers]
100.109.240.84 ansible_user=dranov

[swarm_nodes:children]
swarm_manager
swarm_workers

[server1]
100.99.158.16 ansible_user=kaka-server

[server2]
100.109.240.84 ansible_user=dranov
